/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface ActivityDto {
  id: string;
  /** @nullable */
  actorName?: string | null;
  action: string;
  entityType: string;
  /** @nullable */
  entityId?: string | null;
  changedFields: string[];
  createdAt: string;
}
