/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { PaymentDto } from './paymentDto';

export interface AdminPaymentDto {
  payment: PaymentDto;
  institutionId: string;
  institutionName: string;
}
