/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { PlanDto } from './planDto';

export interface AdminPlanDto {
  plan: PlanDto;
  isActive: boolean;
  sort: number;
  activeSubscriptions: number;
}
