/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface AdminUserDto {
  id: string;
  fullName: string;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  email?: string | null;
  phoneConfirmed: boolean;
  roles: string[];
  institutions: number;
  lockedOut: boolean;
  createdAt: string;
  /** @nullable */
  lastLoginAt?: string | null;
}
