/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface AdminOverview {
  users: number;
  institutions: number;
  paidSubscriptions: number;
  pendingPayments: number;
  revenueThisMonthPoisha: number;
  publishedQuestions: number;
  questionsInReview: number;
  openReports: number;
}
