/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { InstitutionType } from './institutionType';

export interface AdminInstitutionDto {
  id: string;
  name: string;
  type: InstitutionType;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  ownerName?: string | null;
  /** @nullable */
  ownerPhone?: string | null;
  members: number;
  /** @nullable */
  activePlan?: string | null;
  /** @nullable */
  planEndsAt?: string | null;
  createdAt: string;
}
