/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface AnnouncementDto {
  id: string;
  titleBn: string;
  bodyBn: string;
  /** @nullable */
  linkUrl?: string | null;
  startsAt: string;
}
