/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export type AnswerKeyMode = typeof AnswerKeyMode[keyof typeof AnswerKeyMode];


export const AnswerKeyMode = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
