/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { ExamSource } from './examSource';

export interface AppearanceContent {
  source: ExamSource;
  /** @nullable */
  boardId?: string | null;
  /** @nullable */
  schoolName?: string | null;
  year: number;
}
