/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { SessionResponse } from './sessionResponse';

export interface AuthStepResponse {
  otpRequired: boolean;
  /** @nullable */
  phone?: string | null;
  session?: SessionResponse | null;
}
