/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { SearchFilters } from './searchFilters';

export interface AutoSelectQuestionsRequest {
  filters?: SearchFilters | null;
  /** @nullable */
  targetCount?: number | null;
  keepExisting: boolean;
  /** @nullable */
  seed?: number | null;
}
