/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface AutoSelectQuestionsResponse {
  questionIds: string[];
  availableCount: number;
  /** @nullable */
  shortfallMessage?: string | null;
}
