/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export type BankSharing = typeof BankSharing[keyof typeof BankSharing];


export const BankSharing = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
