/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { QuestionCard } from './questionCard';

export interface BankQuestionPage {
  items: QuestionCard[];
  /** @nullable */
  nextCursor?: string | null;
  totalCount: number;
}
