/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { BankSharing } from './bankSharing';

export interface BankDto {
  id: string;
  name: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  levelId?: string | null;
  /** @nullable */
  subjectId?: string | null;
  /** @nullable */
  subjectLabel?: string | null;
  sharing: BankSharing;
  requireApproval: boolean;
  isDefault: boolean;
  questionCount: number;
  pendingCount: number;
  ownerId: string;
  ownerName: string;
  isOwner: boolean;
  canManage: boolean;
  canWrite: boolean;
  createdAt: string;
  updatedAt: string;
}
