/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface BatchDto {
  id: string;
  name: string;
  /** @nullable */
  levelId?: string | null;
  /** @nullable */
  levelName?: string | null;
  /** @nullable */
  year?: number | null;
  studentCount: number;
  createdAt: string;
}
