/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface BoardDto {
  id: string;
  code: string;
  nameBn: string;
  shortBn: string;
}
