/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { BulkAction } from './bulkAction';

export interface BulkBankQuestionsRequest {
  questionIds: string[];
  action: BulkAction;
  /** @nullable */
  targetBankId?: string | null;
  /** @nullable */
  chapterId?: string | null;
  /** @nullable */
  topicId?: string | null;
  /** @nullable */
  value?: number | null;
  /** @nullable */
  tagIds?: string[] | null;
}
