/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { QuestionAction } from './questionAction';

export interface ChangeQuestionStatusRequest {
  action: QuestionAction;
  /** @nullable */
  note?: string | null;
}
