/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { InstitutionRole } from './institutionRole';

export interface ChangeMemberRoleRequest {
  role: InstitutionRole;
}
