/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { StatusCount } from './statusCount';
import type { SubjectCoverage } from './subjectCoverage';

export interface ContentStats {
  byStatus: StatusCount[];
  coverage: SubjectCoverage[];
  openReports: number;
}
