/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface CqPartDto {
  prompt: string;
  marks: number;
  /** @nullable */
  answer?: string | null;
}
