/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { QuestionSource } from './questionSource';
import type { QuestionType } from './questionType';
import type { SetMode } from './setMode';

export interface CreateQuestionSetCommand {
  title: string;
  levelId: string;
  subjectId: string;
  chapterIds: string[];
  type: QuestionType;
  mode: SetMode;
  source: QuestionSource;
  bankIds: string[];
  targetCount: number;
  durationMin: number;
  fullMarks: number;
}
