/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { ImportDefaults } from './importDefaults';
import type { ImportSourceType } from './importSourceType';

export interface CreateImportCommand {
  /** @nullable */
  bankId?: string | null;
  sourceType: ImportSourceType;
  defaults: ImportDefaults;
  /** @nullable */
  fileKey?: string | null;
  /** @nullable */
  fileName?: string | null;
  /** @nullable */
  text?: string | null;
}
