/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface CreateInvitationResponse {
  id: string;
  token: string;
  link: string;
  smsSent: boolean;
}
