/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { AdminUserDto } from './adminUserDto';

export interface CursorPageOfAdminUserDto {
  items: AdminUserDto[];
  /** @nullable */
  nextCursor?: string | null;
}
