/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { QuestionReportDto } from './questionReportDto';

export interface CursorPageOfQuestionReportDto {
  items: QuestionReportDto[];
  /** @nullable */
  nextCursor?: string | null;
}
