/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { ImportJobDto } from './importJobDto';

export interface CursorPageOfImportJobDto {
  items: ImportJobDto[];
  /** @nullable */
  nextCursor?: string | null;
}
