/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { ImportRowDto } from './importRowDto';

export interface CursorPageOfImportRowDto {
  items: ImportRowDto[];
  /** @nullable */
  nextCursor?: string | null;
}
