/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { StudentDto } from './studentDto';

export interface CursorPageOfStudentDto {
  items: StudentDto[];
  /** @nullable */
  nextCursor?: string | null;
}
