/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { ActivityDto } from './activityDto';

export interface CursorPageOfActivityDto {
  items: ActivityDto[];
  /** @nullable */
  nextCursor?: string | null;
}
