/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { AdminPaymentDto } from './adminPaymentDto';

export interface CursorPageOfAdminPaymentDto {
  items: AdminPaymentDto[];
  /** @nullable */
  nextCursor?: string | null;
}
