/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { SetSummaryDto } from './setSummaryDto';

export interface CursorPageOfSetSummaryDto {
  items: SetSummaryDto[];
  /** @nullable */
  nextCursor?: string | null;
}
