/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { AdminInstitutionDto } from './adminInstitutionDto';

export interface CursorPageOfAdminInstitutionDto {
  items: AdminInstitutionDto[];
  /** @nullable */
  nextCursor?: string | null;
}
