/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { AnnouncementDto } from './announcementDto';
import type { DashboardCounters } from './dashboardCounters';
import type { DashboardImpact } from './dashboardImpact';
import type { DashboardSubscription } from './dashboardSubscription';
import type { GrowthPoint } from './growthPoint';
import type { InstitutionType } from './institutionType';
import type { SetSummaryDto } from './setSummaryDto';
import type { SupportDto } from './supportDto';

export interface DashboardDto {
  userName: string;
  institutionName: string;
  /** @nullable */
  institutionAddress?: string | null;
  /** @nullable */
  institutionLogoUrl?: string | null;
  institutionType: InstitutionType;
  counters: DashboardCounters;
  impact: DashboardImpact;
  recentSets: SetSummaryDto[];
  growth: GrowthPoint[];
  /** @nullable */
  lastContentUpdate?: string | null;
  subscription: DashboardSubscription;
  announcements: AnnouncementDto[];
  support: SupportDto;
}
