/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface DashboardCounters {
  sets: number;
  onlineExams: number;
  omrEvaluated: number;
  students: number;
  teachers: number;
  myQuestions: number;
}
