/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface DashboardSubscription {
  hasActivePlan: boolean;
  /** @nullable */
  endsAt?: string | null;
  /** @nullable */
  daysLeft?: number | null;
  renewalDue: boolean;
}
