/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface DraftBoardTag {
  raw: string;
  /** @nullable */
  boardId?: string | null;
  /** @nullable */
  year?: number | null;
}
