/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export type ExportFormat = typeof ExportFormat[keyof typeof ExportFormat];


export const ExportFormat = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
