/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { ExportFormat } from './exportFormat';

export type ExportBankParams = {
format?: ExportFormat;
};
