/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { InstitutionRole } from './institutionRole';

export interface GetInvitationResponse {
  institutionName: string;
  role: InstitutionRole;
  /** @nullable */
  invitedName?: string | null;
  isValid: boolean;
}
