/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface GrantSubscriptionCommand {
  institutionId: string;
  planId: string;
  days: number;
  subjectIds: string[];
}
