/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface HealthResponse {
  status: string;
  version: string;
  database: boolean;
  time: string;
}
