/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { ImportStudentsRowError } from './importStudentsRowError';

export interface ImportStudentsResponse {
  created: number;
  updated: number;
  skipped: number;
  errors: ImportStudentsRowError[];
}
