/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { QuestionType } from './questionType';

export interface ImportDefaults {
  levelId: string;
  subjectId: string;
  /** @nullable */
  chapterId?: string | null;
  type: QuestionType;
  difficulty: number;
}
