/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { ImportMessage } from './importMessage';
import type { ImportRowStatus } from './importRowStatus';
import type { QuestionContent } from './questionContent';
import type { QuestionDraft } from './questionDraft';

export interface ImportRowDto {
  id: string;
  rowNo: number;
  status: ImportRowStatus;
  validatedStatus: ImportRowStatus;
  draft: QuestionDraft;
  messages: ImportMessage[];
  /** @nullable */
  duplicateOfQuestionId?: string | null;
  /** @nullable */
  createdQuestionId?: string | null;
  content: QuestionContent;
}
