/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { ImportColumnDto } from './importColumnDto';
import type { ImportDefaults } from './importDefaults';
import type { ImportJobDtoColumnMap } from './importJobDtoColumnMap';
import type { ImportSourceType } from './importSourceType';
import type { ImportStatus } from './importStatus';
import type { ImportTotals } from './importTotals';

export interface ImportJobDto {
  id: string;
  isPlatform: boolean;
  /** @nullable */
  bankId?: string | null;
  /** @nullable */
  bankName?: string | null;
  sourceType: ImportSourceType;
  /** @nullable */
  fileName?: string | null;
  defaults: ImportDefaults;
  status: ImportStatus;
  totals: ImportTotals;
  detectedHeaders: string[];
  missingColumns: string[];
  columnMap: ImportJobDtoColumnMap;
  columns: ImportColumnDto[];
  /** @nullable */
  error?: string | null;
  /** @nullable */
  createdByName?: string | null;
  createdAt: string;
  updatedAt: string;
  /** @nullable */
  completedAt?: string | null;
  /** @nullable */
  rollbackUntil?: string | null;
  canRollback: boolean;
}
