/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface ImportTotals {
  total: number;
  ok: number;
  warning: number;
  error: number;
  duplicate: number;
  excluded: number;
  imported: number;
}
