/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { InstitutionType } from './institutionType';
import type { PaperSettings } from './paperSettings';

export interface InstitutionDto {
  id: string;
  name: string;
  /** @nullable */
  nameEn?: string | null;
  type: InstitutionType;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  logoUrl?: string | null;
  paperDefaults: PaperSettings;
  createdAt: string;
}
