/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { InstitutionRole } from './institutionRole';
import type { InstitutionType } from './institutionType';

export interface InstitutionMembershipDto {
  institutionId: string;
  name: string;
  role: InstitutionRole;
  type: InstitutionType;
  /** @nullable */
  logoUrl?: string | null;
}
