/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface InvoiceLine {
  descriptionBn: string;
  quantity: number;
  unitPoisha: number;
  totalPoisha: number;
}
