/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { InvoiceLine } from './invoiceLine';
import type { PaymentGateway } from './paymentGateway';

export interface InvoiceDto {
  id: string;
  number: string;
  sellerName: string;
  /** @nullable */
  sellerAddress?: string | null;
  billedToName: string;
  /** @nullable */
  billedToAddress?: string | null;
  lines: InvoiceLine[];
  subtotalPoisha: number;
  vatPoisha: number;
  totalPoisha: number;
  periodStart: string;
  periodEnd: string;
  issuedAt: string;
  tranId: string;
  gateway: PaymentGateway;
}
