/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { JobKind } from './jobKind';
import type { JobState } from './jobState';

export interface JobDto {
  id: string;
  kind: JobKind;
  state: JobState;
  /** @nullable */
  downloadUrl?: string | null;
  /** @nullable */
  error?: string | null;
  createdAt: string;
  /** @nullable */
  completedAt?: string | null;
}
