/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export type JobKind = typeof JobKind[keyof typeof JobKind];


export const JobKind = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
