/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export type ListQuestionSetsParams = {
keyword?: string;
subjectId?: string;
mine?: boolean;
cursor?: string;
limit?: number;
};
