/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export type ListAdminUsersParams = {
keyword?: string;
role?: string;
cursor?: string;
limit?: number;
};
