/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { ImportRowStatus } from './importRowStatus';

export type ListImportRowsParams = {
status?: ImportRowStatus;
cursor?: string;
limit?: number;
};
