/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export type ListStudentsParams = {
batchId?: string;
keyword?: string;
cursor?: string;
limit?: number;
};
