/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { ReportStatus } from './reportStatus';

export type ListQuestionReportsParams = {
status?: ReportStatus;
cursor?: string;
limit?: number;
};
