/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { PaymentStatus } from './paymentStatus';

export type ListAdminPaymentsParams = {
status?: PaymentStatus;
tranId?: string;
cursor?: string;
limit?: number;
};
