/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { ContentStatus } from './contentStatus';
import type { QuestionType } from './questionType';

export type ListBankQuestionsParams = {
status?: ContentStatus;
subjectId?: string;
chapterId?: string;
type?: QuestionType;
tagId?: string;
keyword?: string;
cursor?: string;
limit?: number;
};
