/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { InstitutionRole } from './institutionRole';

export interface MemberDto {
  userId: string;
  fullName: string;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  email?: string | null;
  role: InstitutionRole;
  joinedAt: string;
  /** @nullable */
  lastLoginAt?: string | null;
  isMe: boolean;
}
