/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { InstitutionMembershipDto } from './institutionMembershipDto';

export interface MeResponse {
  id: string;
  fullName: string;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  email?: string | null;
  phoneConfirmed: boolean;
  platformRoles: string[];
  institutions: InstitutionMembershipDto[];
  activeInstitution?: InstitutionMembershipDto | null;
}
