/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export type MessageSeverity = typeof MessageSeverity[keyof typeof MessageSeverity];


export const MessageSeverity = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
