/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export type OtpPurpose = typeof OtpPurpose[keyof typeof OtpPurpose];


export const OtpPurpose = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
