/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export type PaperBlockKind = typeof PaperBlockKind[keyof typeof PaperBlockKind];


export const PaperBlockKind = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
} as const;
