/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface PaperOption {
  label: number;
  originalIndex: number;
  content: string;
  isCorrect: boolean;
}
