/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { AnswerKeyMode } from './answerKeyMode';
import type { OptionLabel } from './optionLabel';
import type { OptionLayout } from './optionLayout';
import type { PaperFont } from './paperFont';
import type { PaperHeader } from './paperHeader';
import type { PaperMargins } from './paperMargins';
import type { PaperSize } from './paperSize';
import type { TextAlignMode } from './textAlignMode';

export interface PaperSettings {
  paperSize: PaperSize;
  marginsMm: PaperMargins;
  columns: number;
  textAlign: TextAlignMode;
  fontFamily: PaperFont;
  fontSizePt: number;
  lineHeight: number;
  optionLayout: OptionLayout;
  optionLabel: OptionLabel;
  pageNumbers: boolean;
  /** @nullable */
  watermark?: string | null;
  header: PaperHeader;
  showBoardTags: boolean;
  markImportant: boolean;
  answerKey: AnswerKeyMode;
  teacherCopy: boolean;
  attachOmr: boolean;
  variants: number;
  shuffleQuestions: boolean;
  shuffleOptions: boolean;
  seed: number;
}
