/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface PaperMargins {
  top: number;
  right: number;
  bottom: number;
  left: number;
}
