/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { QuestionType } from './questionType';

export interface PaperHeaderInfo {
  institutionName: string;
  /** @nullable */
  institutionAddress?: string | null;
  /** @nullable */
  logoUrl?: string | null;
  title: string;
  levelName: string;
  subjectName: string;
  chapterNames: string[];
  durationMin: number;
  fullMarks: number;
  type: QuestionType;
}
