/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface PaperHeader {
  institution: boolean;
  level: boolean;
  subject: boolean;
  chapter: boolean;
  setCodeBox: boolean;
  studentInfoBox: boolean;
  instructions: string;
}
