/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { PaymentGateway } from './paymentGateway';
import type { PaymentStatus } from './paymentStatus';

export interface PaymentDto {
  id: string;
  tranId: string;
  planName: string;
  subjectCount: number;
  amountPoisha: number;
  currency: string;
  gateway: PaymentGateway;
  status: PaymentStatus;
  createdAt: string;
  /** @nullable */
  paidAt?: string | null;
  /** @nullable */
  invoiceId?: string | null;
  /** @nullable */
  invoiceNumber?: string | null;
}
