/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface PlanLimits {
  /** @nullable */
  maxSubjects?: number | null;
  levelSlugs: string[];
  /** @nullable */
  savedSets?: number | null;
  /** @nullable */
  teachers?: number | null;
  /** @nullable */
  students?: number | null;
  /** @nullable */
  customBanks?: number | null;
  /** @nullable */
  customQuestions?: number | null;
  /** @nullable */
  importsPerMonth?: number | null;
  omrTokensIncluded: number;
  /** @nullable */
  onlineExamsPerMonth?: number | null;
}
