/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { DraftBoardTag } from './draftBoardTag';
import type { DraftCqPart } from './draftCqPart';
import type { McqKind } from './mcqKind';
import type { QuestionType } from './questionType';

export interface QuestionDraft {
  type: QuestionType;
  mcqKind?: McqKind | null;
  /** @nullable */
  groupKey?: string | null;
  /** @nullable */
  stimulus?: string | null;
  stem: string;
  statements: string[];
  /** @nullable */
  stemTail?: string | null;
  options: string[];
  /** @nullable */
  correctRaw?: string | null;
  /** @nullable */
  correctIndex?: number | null;
  cqParts: DraftCqPart[];
  /** @nullable */
  explanation?: string | null;
  /** @nullable */
  chapterRef?: string | null;
  /** @nullable */
  chapterId?: string | null;
  /** @nullable */
  topicRef?: string | null;
  /** @nullable */
  topicId?: string | null;
  /** @nullable */
  difficulty?: number | null;
  /** @nullable */
  importance?: number | null;
  boardTags: DraftBoardTag[];
  sourceLocation: string;
}
