/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { ReportStatus } from './reportStatus';

export interface QuestionReportDto {
  id: string;
  questionId: string;
  questionExcerpt: string;
  reason: string;
  status: ReportStatus;
  /** @nullable */
  resolution?: string | null;
  reporterName: string;
  institutionName: string;
  createdAt: string;
  /** @nullable */
  resolvedAt?: string | null;
}
