/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { AppearanceContent } from './appearanceContent';
import type { CqPartContent } from './cqPartContent';
import type { McqKind } from './mcqKind';
import type { OptionContent } from './optionContent';
import type { QuestionType } from './questionType';

export interface QuestionContent {
  type: QuestionType;
  mcqKind?: McqKind | null;
  subjectId: string;
  chapterId: string;
  /** @nullable */
  topicId?: string | null;
  stem: string;
  /** @nullable */
  stimulus?: string | null;
  /** @nullable */
  stimulusId?: string | null;
  options: OptionContent[];
  cqParts: CqPartContent[];
  /** @nullable */
  explanation?: string | null;
  difficulty: number;
  importance: number;
  isMath: boolean;
  isCommon: boolean;
  appearances: AppearanceContent[];
  tagIds: string[];
}
