/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { QuestionCard } from './questionCard';
import type { QuestionContent } from './questionContent';

export interface QuestionDetail {
  card: QuestionCard;
  content: QuestionContent;
  subjectLabel: string;
  /** @nullable */
  reviewNote?: string | null;
  /** @nullable */
  sourceQuestionId?: string | null;
  /** @nullable */
  createdByName?: string | null;
  createdAt: string;
  /** @nullable */
  publishedAt?: string | null;
}
