/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { AnswerKeyEntry } from './answerKeyEntry';
import type { PaperBlock } from './paperBlock';
import type { PaperHeaderInfo } from './paperHeaderInfo';
import type { PaperSettings } from './paperSettings';

export interface RenderedPaper {
  setId: string;
  itemsVersion: number;
  variant: number;
  variantLabel: string;
  header: PaperHeaderInfo;
  settings: PaperSettings;
  blocks: PaperBlock[];
  answerKey: AnswerKeyEntry[];
  questionCount: number;
  totalMarks: number;
}
