/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { ReportStatus } from './reportStatus';

export interface ResolveQuestionReportRequest {
  status: ReportStatus;
  resolution: string;
}
