/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface ReviewBankQuestionRequest {
  approve: boolean;
  /** @nullable */
  note?: string | null;
}
