/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface SaveSubjectRequest {
  levelId: string;
  nameBn: string;
  /** @nullable */
  paper?: number | null;
}
