/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface SaveBatchRequest {
  name: string;
  /** @nullable */
  levelId?: string | null;
  /** @nullable */
  year?: number | null;
}
