/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { BankSharing } from './bankSharing';

export interface SaveBankRequest {
  name: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  levelId?: string | null;
  /** @nullable */
  subjectId?: string | null;
  sharing: BankSharing;
  requireApproval: boolean;
}
