/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { PlanLimits } from './planLimits';
import type { PlanPricing } from './planPricing';

export interface SavePlanRequest {
  code: string;
  nameBn: string;
  /** @nullable */
  descriptionBn?: string | null;
  pricing: PlanPricing;
  pricePoisha: number;
  durationDays: number;
  vatRateBasisPoints: number;
  limits: PlanLimits;
  isActive: boolean;
  sort: number;
}
