/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface SaveChapterRequest {
  subjectId: string;
  /** @nullable */
  number?: number | null;
  nameBn: string;
}
