/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { SaveSetItemsItemInput } from './saveSetItemsItemInput';

export interface SaveSetItemsRequest {
  items: SaveSetItemsItemInput[];
}
