/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { QuestionContent } from './questionContent';

export interface SavePlatformQuestionRequest {
  content: QuestionContent;
  submitForReview: boolean;
}
