/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { QuestionSource } from './questionSource';
import type { SearchFilters } from './searchFilters';

export interface SearchSetQuestionsRequest {
  filters: SearchFilters;
  /** @nullable */
  chapterIds?: string[] | null;
  source?: QuestionSource | null;
  /** @nullable */
  bankIds?: string[] | null;
  /** @nullable */
  cursor?: string | null;
  /** @nullable */
  limit?: number | null;
}
