/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { QuestionSource } from './questionSource';
import type { QuestionType } from './questionType';
import type { SearchFilters } from './searchFilters';

export interface SearchQuestionsQuery {
  subjectId: string;
  chapterIds: string[];
  type?: QuestionType | null;
  source: QuestionSource;
  bankIds: string[];
  filters: SearchFilters;
  /** @nullable */
  cursor?: string | null;
  /** @nullable */
  limit?: number | null;
}
