/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { McqKind } from './mcqKind';
import type { SearchMode } from './searchMode';

export interface SearchFilters {
  /** @nullable */
  keyword?: string | null;
  mode: SearchMode;
  topicIds: string[];
  tagIds: string[];
  /** @nullable */
  isMath?: boolean | null;
  withImage: boolean;
  mcqKind?: McqKind | null;
  repeatedBoard: boolean;
}
