/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { OtpPurpose } from './otpPurpose';

export interface SendOtpCommand {
  phone: string;
  purpose: OtpPurpose;
}
