/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { MeResponse } from './meResponse';

export interface SessionResponse {
  accessToken: string;
  expiresAt: string;
  me: MeResponse;
}
