/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { PaperSettings } from './paperSettings';
import type { QuestionSource } from './questionSource';
import type { QuestionType } from './questionType';
import type { SetBankDto } from './setBankDto';
import type { SetChapterDto } from './setChapterDto';
import type { SetItemDto } from './setItemDto';
import type { SetMode } from './setMode';

export interface SetDetailDto {
  id: string;
  title: string;
  levelId: string;
  levelName: string;
  subjectId: string;
  subjectLabel: string;
  chapters: SetChapterDto[];
  type: QuestionType;
  mode: SetMode;
  source: QuestionSource;
  banks: SetBankDto[];
  targetCount: number;
  durationMin: number;
  fullMarks: number;
  settings: PaperSettings;
  itemsVersion: number;
  items: SetItemDto[];
  totalMarks: number;
  hasSubjectAccess: boolean;
  institutionName: string;
  /** @nullable */
  institutionLogoUrl?: string | null;
  createdAt: string;
  updatedAt: string;
}
