/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { SetImportColumnMapRequestColumnMap } from './setImportColumnMapRequestColumnMap';

export interface SetImportColumnMapRequest {
  columnMap: SetImportColumnMapRequestColumnMap;
}
