/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { QuestionSource } from './questionSource';
import type { QuestionType } from './questionType';

export interface SetSummaryDto {
  id: string;
  title: string;
  levelName: string;
  subjectId: string;
  subjectLabel: string;
  type: QuestionType;
  itemCount: number;
  targetCount: number;
  durationMin: number;
  fullMarks: number;
  source: QuestionSource;
  /** @nullable */
  createdByName?: string | null;
  isMine: boolean;
  createdAt: string;
  updatedAt: string;
}
