/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { ContentStatus } from './contentStatus';

export interface StatusCount {
  status: ContentStatus;
  count: number;
}
