/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface StudentDto {
  id: string;
  batchId: string;
  batchName: string;
  roll: string;
  name: string;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  guardianPhone?: string | null;
  /** @nullable */
  email?: string | null;
  createdAt: string;
}
