/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface SubjectCoverage {
  subjectId: string;
  label: string;
  published: number;
  mcq: number;
  cq: number;
}
