/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { PlanLimits } from './planLimits';
import type { SubscriptionDto } from './subscriptionDto';
import type { UsageDto } from './usageDto';

export interface SubscriptionSummaryDto {
  hasActivePlan: boolean;
  allSubjects: boolean;
  subjectIds: string[];
  levelSlugs: string[];
  /** @nullable */
  endsAt?: string | null;
  /** @nullable */
  daysLeft?: number | null;
  renewalDue: boolean;
  limits: PlanLimits;
  usage: UsageDto[];
  subscriptions: SubscriptionDto[];
}
