/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { PlanPricing } from './planPricing';

export interface SubscriptionDto {
  id: string;
  planName: string;
  pricing: PlanPricing;
  allSubjects: boolean;
  subjectLabels: string[];
  startsAt: string;
  endsAt: string;
  isActive: boolean;
  isTrial: boolean;
}
