/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */

export interface SupportDto {
  phone: string;
  email: string;
  /** @nullable */
  whatsApp?: string | null;
  /** @nullable */
  messenger?: string | null;
  hours: string;
}
