/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { PaperSettings } from './paperSettings';

export interface UpdatePaperDefaultsCommand {
  settings: PaperSettings;
}
