/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { ImportRowDto } from './importRowDto';
import type { ImportTotals } from './importTotals';

export interface UpdateImportRowResponse {
  row: ImportRowDto;
  totals: ImportTotals;
  affectedRowIds: string[];
}
