/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { QuestionDraft } from './questionDraft';

export interface UpdateImportRowRequest {
  draft?: QuestionDraft | null;
  /** @nullable */
  excluded?: boolean | null;
}
