/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { ImportSourceType } from './importSourceType';

export interface UploadImportFileResponse {
  fileKey: string;
  fileName: string;
  size: number;
  sourceType: ImportSourceType;
}
