/**
 * Generated by orval 🍺
 * Do not edit manually.
 * e-proshno API
 * OpenAPI spec version: v1
 */
import type { LimitKey } from './limitKey';

export interface UsageDto {
  key: LimitKey;
  used: number;
  /** @nullable */
  limit?: number | null;
}
