using System.Security.Cryptography;
using System.Text;
using Amazon.Runtime;
using Amazon.S3;
using Amazon.S3.Model;
using Amazon.S3.Util;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Options;

namespace EProshno.Infrastructure.Storage;

public sealed class StorageOptions
{
    public const string Section = "Storage";

    /// <summary>"Local" (files under LocalPath) or "S3" (R2/MinIO).</summary>
    public string Provider { get; set; } = "Local";

    public string LocalPath { get; set; } = ".data/storage";
    public string ServiceUrl { get; set; } = "";
    public string Bucket { get; set; } = "eproshno";
    public string AccessKey { get; set; } = "";
    public string SecretKey { get; set; } = "";

    /// <summary>HMAC key for signed download links served by the API.</summary>
    public string UrlSigningKey { get; set; } = "";
}

public sealed record StoredObject(Stream Content, string ContentType, long? Length);

public interface IObjectStorage
{
    Task PutAsync(string key, Stream content, string contentType, CancellationToken ct);

    Task<StoredObject?> GetAsync(string key, CancellationToken ct);

    Task<bool> ExistsAsync(string key, CancellationToken ct);

    Task DeleteAsync(string key, CancellationToken ct);
}

public static class StorageKeys
{
    public static string Media(Guid? institutionId, string extension) =>
        $"media/{institutionId?.ToString("N") ?? "platform"}/{Token()}{extension}";

    public static string Logo(Guid institutionId, string extension) => $"logos/{institutionId:N}/{Token()}{extension}";

    public static string Import(Guid institutionId, string extension) => $"imports/{institutionId:N}/{Token()}{extension}";

    public static string Pdf(Guid institutionId, string cacheKey) => $"pdf/{institutionId:N}/{cacheKey}.pdf";

    /// <summary>Keys are generated by us; this guards against traversal when a key arrives in a URL.</summary>
    public static bool IsSafe(string key) =>
        key.Length is > 0 and <= 300
        && !key.Contains("..", StringComparison.Ordinal)
        && !key.StartsWith('/')
        && key.All(c => char.IsAsciiLetterOrDigit(c) || c is '/' or '-' or '_' or '.');

    public static string ContentTypeFor(string key) => Path.GetExtension(key).ToLowerInvariant() switch
    {
        ".png" => "image/png",
        ".jpg" or ".jpeg" => "image/jpeg",
        ".webp" => "image/webp",
        ".pdf" => "application/pdf",
        ".xlsx" => "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        ".csv" => "text/csv; charset=utf-8",
        ".json" => "application/json",
        ".zip" => "application/zip",
        _ => "application/octet-stream",
    };

    // 128 random bits: media keys are served without auth, so they must be unguessable.
    private static string Token() => Convert.ToHexString(RandomNumberGenerator.GetBytes(16)).ToLowerInvariant();
}

/// <summary>Development storage on disk. Relative paths resolve against the host's content root.</summary>
public sealed class LocalObjectStorage(IOptions<StorageOptions> options, IHostEnvironment environment) : IObjectStorage
{
    private readonly string _root =
        Path.GetFullPath(Path.Combine(environment.ContentRootPath, options.Value.LocalPath)) + Path.DirectorySeparatorChar;

    public async Task PutAsync(string key, Stream content, string contentType, CancellationToken ct)
    {
        var path = PathFor(key);
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        await using var file = File.Create(path);
        await content.CopyToAsync(file, ct);
    }

    public Task<StoredObject?> GetAsync(string key, CancellationToken ct)
    {
        var path = PathFor(key);
        if (!File.Exists(path))
        {
            return Task.FromResult<StoredObject?>(null);
        }

        Stream stream = File.OpenRead(path);
        return Task.FromResult<StoredObject?>(new StoredObject(stream, StorageKeys.ContentTypeFor(key), stream.Length));
    }

    public Task<bool> ExistsAsync(string key, CancellationToken ct) => Task.FromResult(File.Exists(PathFor(key)));

    public Task DeleteAsync(string key, CancellationToken ct)
    {
        var path = PathFor(key);
        if (File.Exists(path))
        {
            File.Delete(path);
        }

        return Task.CompletedTask;
    }

    private string PathFor(string key)
    {
        if (!StorageKeys.IsSafe(key))
        {
            throw new ArgumentException("Unsafe storage key.", nameof(key));
        }

        var path = Path.GetFullPath(Path.Combine(_root, key));
        return path.StartsWith(_root, StringComparison.Ordinal) ? path : throw new ArgumentException("Unsafe storage key.", nameof(key));
    }
}

public sealed class S3ObjectStorage : IObjectStorage, IDisposable
{
    private readonly AmazonS3Client _client;
    private readonly string _bucket;
    private readonly SemaphoreSlim _bucketCheck = new(1, 1);
    private bool _bucketReady;

    public S3ObjectStorage(IOptions<StorageOptions> options)
    {
        var o = options.Value;
        _bucket = o.Bucket;
        _client = new AmazonS3Client(
            new BasicAWSCredentials(o.AccessKey, o.SecretKey),
            new AmazonS3Config { ServiceURL = o.ServiceUrl, ForcePathStyle = true, AuthenticationRegion = "auto" });
    }

    public async Task PutAsync(string key, Stream content, string contentType, CancellationToken ct)
    {
        await EnsureBucketAsync(ct);
        await _client.PutObjectAsync(new PutObjectRequest
        {
            BucketName = _bucket,
            Key = key,
            InputStream = content,
            ContentType = contentType,
            AutoCloseStream = false,
        }, ct);
    }

    public async Task<StoredObject?> GetAsync(string key, CancellationToken ct)
    {
        try
        {
            var response = await _client.GetObjectAsync(_bucket, key, ct);
            return new StoredObject(response.ResponseStream, response.Headers.ContentType ?? StorageKeys.ContentTypeFor(key), response.ContentLength);
        }
        catch (AmazonS3Exception ex) when (ex.StatusCode == System.Net.HttpStatusCode.NotFound)
        {
            return null;
        }
    }

    public async Task<bool> ExistsAsync(string key, CancellationToken ct)
    {
        try
        {
            await _client.GetObjectMetadataAsync(_bucket, key, ct);
            return true;
        }
        catch (AmazonS3Exception ex) when (ex.StatusCode == System.Net.HttpStatusCode.NotFound)
        {
            return false;
        }
    }

    public async Task DeleteAsync(string key, CancellationToken ct) => await _client.DeleteObjectAsync(_bucket, key, ct);

    public void Dispose()
    {
        _client.Dispose();
        _bucketCheck.Dispose();
    }

    private async Task EnsureBucketAsync(CancellationToken ct)
    {
        if (_bucketReady)
        {
            return;
        }

        await _bucketCheck.WaitAsync(ct);
        try
        {
            if (!await AmazonS3Util.DoesS3BucketExistV2Async(_client, _bucket))
            {
                await _client.PutBucketAsync(_bucket, ct);
            }

            _bucketReady = true;
        }
        finally
        {
            _bucketCheck.Release();
        }
    }
}

/// <summary>HMAC-signed, expiring download links for private files (PDFs, exports) streamed by the API.</summary>
public sealed class FileUrlSigner(IOptions<StorageOptions> options, TimeProvider clock)
{
    private readonly byte[] _key = Encoding.UTF8.GetBytes(options.Value.UrlSigningKey);

    public string CreateUrl(string key, TimeSpan lifetime, string? downloadName = null)
    {
        var exp = clock.GetUtcNow().Add(lifetime).ToUnixTimeSeconds();
        var url = $"/api/v1/files/{key}?exp={exp}&sig={Sign(key, exp)}";
        return downloadName is null ? url : $"{url}&name={Uri.EscapeDataString(downloadName)}";
    }

    public bool IsValid(string key, long exp, string sig) =>
        exp >= clock.GetUtcNow().ToUnixTimeSeconds()
        && CryptographicOperations.FixedTimeEquals(Encoding.ASCII.GetBytes(Sign(key, exp)), Encoding.ASCII.GetBytes(sig));

    private string Sign(string key, long exp) =>
        Convert.ToHexString(HMACSHA256.HashData(_key, Encoding.UTF8.GetBytes($"{key}|{exp}"))).ToLowerInvariant();
}
